CREATE TABLE IF NOT EXISTS chat_journal (
    message_index   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    message_type    VARCHAR(20) NOT NULL,
    content         CLOB NOT NULL,
    tokens          INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_journal_conversation_id ON chat_journal (conversation_id);
