CREATE TABLE chat_journal (
    message_index   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR2(255) NOT NULL,
    message_type    VARCHAR2(20) NOT NULL,
    content         CLOB NOT NULL,
    tokens          NUMBER(10) NOT NULL
);

CREATE INDEX idx_chat_journal_conversation_id ON chat_journal (conversation_id);
